Hw02 express
Klaus-Dnlk/nodejs-hw02-express-rest-api pull request #1
Opened 2021-12-17 22:10 UTC by Klaus-Dnlk

Надеюсь попал, куда целился.
Проверьте, пожалуйста.

2021-12-19 10:24 UTC, KirillKulakow commented on model/index.js
> +  // if(name === undefined || email === undefined || phone === undefined) {
удалить комментарии

2021-12-19 10:25 UTC, KirillKulakow commented on model/index.js
> +  writeContent(contacts)
эта функция асинхронная

2021-12-19 10:25 UTC, KirillKulakow commented on model/index.js
>  // const contacts = require('./contacts.json')
удалить комментарии

2021-12-19 10:26 UTC, KirillKulakow requested changes
need fix

2021-12-20 20:22 UTC, KirillKulakow commented on model/index.js
> +  if(!filteredContacts){
что это за проверка, на что?

2021-12-20 20:22 UTC, KirillKulakow requested changes
Need fix

2021-12-20 20:32 UTC, Klaus-Dnlk commented on model/index.js
> +  if(!filteredContacts){
1. существует ли такой контакт (есть ли что удалять вообще или такого контакта нет)
2. когда начинал делать домашку, id  в contacts.json из бойлерплейта нужно было в строку переводить.

2021-12-21 21:51 UTC, Klaus-Dnlk commented on model/index.js
> +  if(!filteredContacts){
так что? удалять? оставлять? или -1 за инициативу?)

2021-12-22 16:54 UTC, KirillKulakow approved these changes

2021-12-22 16:56 UTC, merged